//! The two public cipher variants. Both are thin, identically-shaped wrappers over [`BlowfishCore`],
//! differing only in two constants baked in at construction: whether the key schedule folds bytes in
//! as signed, and the block-word byte order. They are separate named types on purpose, so "which
//! variant" is a compile-time fact a caller cannot get wrong; the shared body is generated by macro
//! so the two cannot drift apart.

use super::{BlowfishCore, Endian};

/// Define a public Blowfish variant wrapping [`BlowfishCore`] with a fixed key-schedule signedness
/// and block endianness. Leading doc attributes are emitted on the generated type.
macro_rules! blowfish_variant {
    (
        $(#[$doc:meta])*
        $name:ident, sign_extend = $sign_extend:expr, endian = $endian:expr $(,)?
    ) => {
        $(#[$doc])*
        pub struct $name {
            core: BlowfishCore,
        }

        impl $name {
            /// Run the key schedule over `key`.
            #[must_use]
            pub fn new(key: &[u8]) -> Self {
                Self {
                    core: BlowfishCore::new(key, $sign_extend, $endian),
                }
            }

            /// Encrypt `data`, zero-padded to an 8-byte multiple.
            #[must_use]
            pub fn encrypt(&self, data: &[u8]) -> Vec<u8> {
                self.core.encrypt_ecb(data)
            }

            /// Decrypt `data` (a multiple of 8 bytes).
            #[must_use]
            pub fn decrypt(&self, data: &[u8]) -> Vec<u8> {
                self.core.decrypt_ecb(data)
            }

            #[cfg(test)]
            pub(crate) fn state_dump(&self) -> String {
                self.core.state_dump()
            }
        }
    };
}

blowfish_variant! {
    /// Zero-padded ECB Blowfish in canonical big-endian block order.
    ///
    /// Textbook Blowfish: unsigned key schedule, big-endian blocks. Built for the ticket path; it
    /// matches published Blowfish test vectors.
    Blowfish, sign_extend = false, endian = Endian::Big,
}

blowfish_variant! {
    /// Zero-padded ECB Blowfish with the signed-byte key schedule and little-endian blocks.
    ///
    /// The SE launcher variant. Its key schedule folds each key byte in as **signed**, so any key
    /// byte >= 0x80 sign-extends into the high bits and the result diverges from textbook Blowfish.
    /// This is reproduced deliberately (SE ships it, so byte-identity requires it) and pinned by the
    /// high-byte golden. The launch-argument key is ASCII hex (all bytes < 0x80), so the divergence
    /// is dormant there but is tested explicitly so it can never drift unnoticed. Blocks are
    /// little-endian.
    LegacyBlowfish, sign_extend = true, endian = Endian::Little,
}
