//! The path hash, pinned against a corpus of real game paths.
//!
//! The corpus is twenty thousand paths generated by the families in [`corpus`], the same rules the
//! recording used. `tests/fixtures/hash_pairs.json` carries the sha256 of every path's three hashes,
//! produced out of process by an independent CRC-32 implementation and validated by looking each path
//! up in a real install: eleven thousand of them are files that install actually holds, and the
//! `.index` (folder hash + file-name hash) and `.index2` (whole-path hash) agreed on the archive, dat
//! file and offset for every one of those. The hermetic test recomputes the digest and the recorded
//! samples; the install-gated test re-runs the resolution and the agreement.

use std::error::Error;
use std::fmt::Write as _;
use std::path::Path;

use apogee_sqpack::{GameData, IndexKind, hash_path};
use serde_json::Value;

type R<T> = Result<T, Box<dyn Error>>;

/// Icon paths: `ui/icon/{group}/{id}.tex`, grouped a thousand to a folder.
fn icons(count: u32, high_resolution: bool) -> Vec<String> {
    (1..=count)
        .map(|i| {
            let suffix = if high_resolution { "_hr1" } else { "" };
            format!("ui/icon/{:06}/{:06}{suffix}.tex", (i / 1000) * 1000, i)
        })
        .collect()
}

/// Equipment models: one folder per equipment id, one file per race and slot.
fn equipment(ids: u32, races: &[&str], slots: &[&str]) -> Vec<String> {
    let mut out = Vec::new();
    for id in 1..=ids {
        for race in races {
            for slot in slots {
                out.push(format!(
                    "chara/equipment/e{id:04}/model/c{race}e{id:04}_{slot}.mdl"
                ));
            }
        }
    }
    out
}

/// Monster and weapon models: one folder per model and body, and a deep path to exercise the split.
fn bodies(prefix: char, kind: &str, models: u32, count: u32) -> Vec<String> {
    let mut out = Vec::new();
    for model in 1..=models {
        for body in 1..=count {
            out.push(format!(
                "chara/{kind}/{prefix}{model:04}/obj/body/b{body:04}/model/{prefix}{model:04}b{body:04}.mdl"
            ));
        }
    }
    out
}

/// The corpus by family, in the order the recording walked it. Keeping the families apart is what
/// lets the resolution floor be applied per family: a total alone would let a whole shape of path
/// stop resolving without the number moving much.
fn families() -> Vec<(&'static str, Vec<String>)> {
    vec![
        ("icon", icons(6000, false)),
        ("icon_hr", icons(3000, true)),
        (
            "equipment",
            equipment(900, &["0101", "0201"], &["top", "dwn", "met", "glv", "sho"]),
        ),
        ("monster", bodies('m', "monster", 600, 2)),
        ("weapon", bodies('w', "weapon", 800, 2)),
    ]
}

/// The corpus, flattened.
fn corpus() -> Vec<String> {
    families()
        .into_iter()
        .flat_map(|(_, paths)| paths)
        .collect()
}

/// One `path<TAB>folder<TAB>file<TAB>whole` line per path, lowercase hex, in corpus order.
fn hash_stream(paths: &[String]) -> String {
    let mut out = String::new();
    for path in paths {
        let h = hash_path(path);
        let _ = writeln!(
            out,
            "{path}\t{:08x}\t{:08x}\t{:08x}",
            h.folder, h.file, h.full
        );
    }
    out
}

fn fixture() -> R<Value> {
    let raw = include_str!("fixtures/hash_pairs.json");
    Ok(serde_json::from_str(raw)?)
}

fn field_str<'a>(v: &'a Value, key: &str) -> R<&'a str> {
    v[key]
        .as_str()
        .ok_or_else(|| format!("missing string field {key}").into())
}

fn field_u64(v: &Value, key: &str) -> R<u64> {
    v[key]
        .as_u64()
        .ok_or_else(|| format!("missing integer field {key}").into())
}

fn field_hex(v: &Value, key: &str) -> R<u32> {
    Ok(u32::from_str_radix(field_str(v, key)?, 16)?)
}

fn samples(doc: &Value) -> R<&Vec<Value>> {
    doc["samples"]
        .as_array()
        .ok_or_else(|| "samples is not an array".into())
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    Sha256::digest(bytes)
        .iter()
        .fold(String::new(), |mut s, b| {
            let _ = write!(s, "{b:02x}");
            s
        })
}

#[test]
fn the_generated_corpus_hashes_to_the_recorded_digest() -> R<()> {
    let doc = fixture()?;
    let paths = corpus();
    assert_eq!(paths.len() as u64, field_u64(&doc, "path_count")?);
    // The gate's bar: the hash is pinned against well over ten thousand recorded pairs.
    assert!(paths.len() >= 10_000, "corpus is {} paths", paths.len());
    assert_eq!(
        sha256_hex(hash_stream(&paths).as_bytes()),
        field_str(&doc, "digest_sha256")?,
        "the corpus no longer hashes to the recorded digest; the samples below say which value moved"
    );
    Ok(())
}

#[test]
fn every_recorded_sample_hashes_to_its_recorded_crcs() -> R<()> {
    // The triage half of the digest above: a handful of paths spelled out, so a break names a value
    // rather than a checksum. Two pairs among them share a whole-path hash, which is what the
    // collision table exists for.
    let doc = fixture()?;
    for sample in samples(&doc)? {
        let path = field_str(sample, "path")?;
        let hash = hash_path(path);
        assert_eq!(
            hash.folder,
            field_hex(sample, "folder_crc")?,
            "{path} folder"
        );
        assert_eq!(hash.file, field_hex(sample, "file_crc")?, "{path} file");
        assert_eq!(
            hash.full,
            field_hex(sample, "path_crc")?,
            "{path} whole path"
        );
        assert_eq!(
            hash.key(),
            (u64::from(hash.folder) << 32) | u64::from(hash.file),
            "{path} key"
        );
    }
    Ok(())
}

#[test]
fn the_recorded_collisions_really_collide() -> R<()> {
    // Two distinct paths hashing to one whole-path value is the case an `.index2` cannot answer on
    // its own. If a change to the hash made these stop colliding, the collision paths below would
    // silently stop being exercised anywhere.
    let doc = fixture()?;
    let mut whole: Vec<(u32, &str)> = Vec::new();
    for sample in samples(&doc)? {
        whole.push((
            hash_path(field_str(sample, "path")?).full,
            field_str(sample, "path")?,
        ));
    }
    let colliding = whole
        .iter()
        .filter(|(h, p)| whole.iter().any(|(h2, p2)| h2 == h && p2 != p))
        .count();
    assert_eq!(
        colliding, 4,
        "expected two colliding pairs among the samples"
    );
    Ok(())
}

/// Re-run the recording against the real install named by `APOGEE_SQPACK_REAL_INSTALL`: every sample
/// resolves where it was recorded, and the whole corpus resolves the same way through both index
/// forms. `#[ignore]` so the hermetic suite stays install-free.
#[test]
#[ignore = "set APOGEE_SQPACK_REAL_INSTALL to a real game subtree to run"]
fn the_corpus_resolves_the_same_way_through_both_index_forms() -> R<()> {
    let root = std::env::var("APOGEE_SQPACK_REAL_INSTALL")?;
    let game = GameData::open(Path::new(&root))?;
    let doc = fixture()?;

    for sample in samples(&doc)? {
        let path = field_str(sample, "path")?;
        let Some(archive) = sample.get("archive").and_then(Value::as_str) else {
            continue; // recorded as generated-but-absent
        };
        let found = game
            .lookup(path)?
            .ok_or_else(|| format!("{path} no longer resolves"))?;
        assert_eq!(found.archive.stem(), archive, "{path} archive");
        assert_eq!(found.dat as u64, field_u64(sample, "dat")?, "{path} dat");
        assert_eq!(found.offset, field_u64(sample, "offset")?, "{path} offset");
    }

    let mut probed = 0u64;
    for (name, paths) in families() {
        let recorded = recorded_family(&doc, name)?;
        let mut resolved = 0u64;
        for path in &paths {
            probed += 1;
            let one = game.lookup_in(path, IndexKind::Index1)?;
            let two = game.lookup_in(path, IndexKind::Index2)?;
            match (&one, &two) {
                (Some(a), Some(b)) => {
                    resolved += 1;
                    assert_eq!(
                        (a.repo, a.archive, a.dat, a.offset),
                        (b.repo, b.archive, b.dat, b.offset),
                        "{path}: the two index forms disagree"
                    );
                }
                (None, None) => {}
                _ => panic!("{path}: resolved through one index form but not the other"),
            }
        }
        // A patch may add or drop files, so this is a floor rather than an equality; per family
        // rather than over the total, so one shape of path cannot stop resolving unnoticed.
        assert!(
            resolved * 10 >= recorded * 9,
            "{name}: only {resolved} of {} paths resolved, against {recorded} recorded",
            paths.len()
        );
    }
    assert_eq!(probed, field_u64(&doc, "path_count")?);

    // The two colliding pairs, asked through the form whose key they collide on. This is the only
    // place the collision table is exercised through the install: an ordinary lookup answers from the
    // `.index`, whose 64-bit key does not collide anywhere in a retail install.
    for sample in samples(&doc)? {
        let path = field_str(sample, "path")?;
        if !colliding(&doc, path)? {
            continue;
        }
        let found = game
            .lookup_in(path, IndexKind::Index2)?
            .ok_or_else(|| format!("{path} no longer resolves through its collision table"))?;
        assert_eq!(found.dat as u64, field_u64(sample, "dat")?, "{path} dat");
        assert_eq!(found.offset, field_u64(sample, "offset")?, "{path} offset");
    }
    Ok(())
}

/// How many of a family the recording saw resolve.
fn recorded_family(doc: &Value, name: &str) -> R<u64> {
    doc["families"]
        .as_array()
        .and_then(|rows| rows.iter().find(|row| row["name"].as_str() == Some(name)))
        .and_then(|row| row["resolved"].as_u64())
        .ok_or_else(|| format!("no recorded family {name}").into())
}

/// Whether another sample shares this one's whole-path hash.
fn colliding(doc: &Value, path: &str) -> R<bool> {
    let hash = hash_path(path).full;
    for other in samples(doc)? {
        let other = field_str(other, "path")?;
        if other != path && hash_path(other).full == hash {
            return Ok(true);
        }
    }
    Ok(false)
}
